id: P006975
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5005
  title: གསོ་བ་རིག་པའི་ཚིག་མཛོད་གཡུ་ཐོག་དགོངས་རྒྱན།
  author: ''
  volumes:
    649caec197bf48d9be4f453c527106ee:
      image_group_id: I3CN5007
      title: ''
      volume_number: 1
      total_pages: 800
ebook_metadata:
  title: གསོ་བ་རིག་པའི་ཚིག་མཛོད་གཡུ་ཐོག་དགོངས་རྒྱན།
  author: ''
  sku: P006975
  cover: cover.jpg
  layers:
  - pagination
