id: I467B8C48
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:47:25+00:00'
last_modified: '2022-06-08T09:41:52.564433+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5005
  title: གསོ་བ་རིག་པའི་ཚིག་མཛོད་གཡུ་ཐོག་དགོངས་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8C4C:
      image_group_id: I3CN5007
      title: Volume 1 of gso ba rig pa'i tshig mdzod g.yu thog dgongs rgyan/
      total_pages: 800
      order: 1
      base_file: 8C4C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
